Repository ESE-Peasy/PosturePerfection, pull requests merged in 2021-03, with the labels that each got.

#55 49 implement post processing
  src/CMakeLists.txt
  src/doubler.cpp
  src/doubler.h
  src/iir.cpp
  src/iir.h
  src/inference_core.cpp
  src/inference_core.h
  src/intermediate_structures.h
  src/main.cpp
  src/post_processor.cpp
  src/post_processor.h
  test.sh
  test/CMakeLists.txt
  test/test.cpp
  test/test_iir.cpp
  test/test_post_processor.cpp
Labels: code, post-processing, testing

#62 60 fix installation
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug

#61 PreProcessor implementation
  README.md
  docs/Doxyfile
  docs/images/logo.png
  install.sh
  install_dependencies.sh
  person2.jpeg
  src/CMakeLists.txt
  src/inference_core.cpp
  src/intermediate_structures.h
  src/main.cpp
  src/pre_processor.cpp
  src/pre_processor.h
  test.sh
  test/CMakeLists.txt
  test/test_pre_processor.cpp
Labels: code, pre-processing

#68 Add body part averaging to post processor
  src/intermediate_structures.h
  src/post_processor.cpp
  src/post_processor.h
  test/test_post_processor.cpp
Labels: code, post-processing

#69 Installation script and improved build script
  .github/PULL_REQUEST_TEMPLATE.md
  CMakeLists.txt
  PosturePerfection_install.sh
  README.md
  docs/software-install.md
  install.sh
  scripts/build.sh
  scripts/install_dependencies.sh
  test.sh
Labels: documentation, installation

#70 Update README.md
  README.md
Labels: documentation

#72 64 posture estimating and post processor
  .gitignore
  person2.jpeg
  src/CMakeLists.txt
  src/intermediate_structures.h
  src/main.cpp
  src/post_processor.cpp
  src/post_processor.h
  src/posture_estimator.cpp
  src/posture_estimator.h
  test/CMakeLists.txt
  test/test_post_processor.cpp
  test/test_posture_estimator.cpp
Labels: code, modelling-system, post-processing

#75 59 multi threading
  docs/html/dir_68267d1309a1af8e8297ef4c3efbcdba.html
  docs/html/files.html
  docs/html/inference__core_8h.html
  docs/html/inference__core_8h__incl.map
  docs/html/inference__core_8h__incl.md5
  docs/html/inference__core_8h__incl.png
  docs/html/inference__core_8h_source.html
  docs/html/intermediate__structures_8cpp.html
  docs/html/intermediate__structures_8cpp__incl.map
  docs/html/intermediate__structures_8cpp__incl.md5
  docs/html/intermediate__structures_8cpp__incl.png
  docs/html/intermediate__structures_8h.html
  docs/html/intermediate__structures_8h__dep__incl.map
  docs/html/intermediate__structures_8h__dep__incl.md5
  docs/html/intermediate__structures_8h__dep__incl.png
  docs/html/intermediate__structures_8h__incl.map
  docs/html/intermediate__structures_8h__incl.md5
  docs/html/intermediate__structures_8h__incl.png
  docs/html/intermediate__structures_8h_source.html
  docs/html/post__processor_8h.html
  docs/html/post__processor_8h__incl.map
  docs/html/post__processor_8h__incl.md5
  docs/html/post__processor_8h__incl.png
  docs/html/post__processor_8h_source.html
  docs/html/posture__estimator_8h.html
  docs/html/posture__estimator_8h__incl.map
  docs/html/posture__estimator_8h__incl.md5
  docs/html/posture__estimator_8h__incl.png
  docs/html/pre__processor_8h.html
  docs/html/pre__processor_8h__incl.map
  docs/html/pre__processor_8h__incl.md5
  docs/html/pre__processor_8h__incl.png
  docs/html/pre__processor_8h_source.html
  docs/html/search/all_3.js
  docs/html/search/all_4.js
  docs/html/search/all_5.js
  src/CMakeLists.txt
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/inference_core.cpp
  src/main.cpp
  src/pipeline.cpp
  src/pipeline.h
  src/pre_processor.cpp
Labels: code

#82 Update documentation
  docs/Doxyfile
  docs/doxygen-homepage.md
  docs/images/PlantUML/sequence-diagram.plantuml
  docs/images/logo.png
  docs/images/sequence-diagram.png
  docs/system/sequence-diagram.md
  person.jpg
  person2.jpeg
  src/gui/main.cpp
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/iir.h
  src/inference_core.cpp
  src/inference_core.h
  src/intermediate_structures.h
  src/main.cpp
  src/notifications/client.h
  src/notifications/notify.h
  src/notifications/server.h
  src/pipeline.h
  src/post_processor.h
  src/posture_estimator.cpp
  src/posture_estimator.h
  src/posture_in.h
  src/pre_processor.h
  testimg.jpg
Labels: documentation

#84 Updated installation script
  PosturePerfection_install.sh
  README.md
Labels: documentation, installation

#95 86 changes to pipeline interface
  src/pipeline.cpp
  src/pipeline.h
Labels: code, pipeline

#96 77 refactor multipage functionality
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
Labels: code

#100 Overlay lines for posture
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/pipeline.cpp
  src/pipeline.h
  src/pre_processor.cpp
Labels: gui, pipeline

#102 99 Create Settings Page
  images/logo.png
  src/gui/CMakeLists.txt
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/main.cpp
  src/pipeline.cpp
  src/pipeline.h
  src/posture_estimator.cpp
  src/posture_estimator.h
  test/test_posture_estimator.cpp
Labels: gui

#106 Fix installing image
  PosturePerfection_install.sh
Labels: bug
