Repository ESE-Peasy/PosturePerfection, pull requests merged in 2021-02, with the labels that each got.

#20 Created templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#24 GitHub Pages updates
  docs/about-us.md
  docs/ci.md
  docs/components.md
  docs/guidance.md
  docs/index.md
  docs/requirements/requirements.md
  docs/requirements/spec.md
  docs/requirements/user-stories.md
  docs/source-documentation.md
Labels: documentation

#37 Initial model testing
  .github/workflows/CI.yml
  README.md
  docs/ci.md
  docs/components.md
  docs/guidance.md
  docs/software-install.md
  docs/source-documentation.md
  docs/sys_design.md
  install.sh
  install_dependencies.sh
  models/EfficientPoseRT_LITE.tflite
  person.jpg
  src/CMakeLists.txt
  src/inference_core.cpp
  src/inference_core.h
  src/main.cpp
  src/posture_in.h
Labels: code, modelling-system

#43 42 interface for post processor output
  .github/workflows/CI.yml
  docs/ci.md
  models/README.md
  src/hello.cpp
  src/hello.h
  src/inference_core.cpp
  src/inference_core.h
  src/main.cpp
  src/post_processor.h
  src/posture_in.h
Labels: code, post-processing

#44 Interface for PreProcessor
  src/inference_core.cpp
  src/inference_core.h
  src/main.cpp
  src/pre_processor.h
Labels: code, pre-processing

#47 Add template test
  .github/workflows/CI.yml
  CMakeLists.txt
  README.md
  install.sh
  install_dependencies.sh
  src/CMakeLists.txt
  src/doubler.cpp
  src/doubler.h
  test/CMakeLists.txt
  test/test.cpp
Labels: testing

#46 Interface for Pose Estimation
  src/posture_estimating.h
Labels: code, modelling-system

#45 Internal Interfaces
  .github/workflows/CI.yml
  docs/ci.md
  models/README.md
  src/gui/interface/Header Files/datapage.h
  src/gui/interface/Header Files/fullscreen.h
  src/gui/interface/Header Files/mainwindow.h
  src/gui/interface/Header Files/settingspage.h
  src/hello.cpp
  src/hello.h
  src/inference_core.cpp
  src/inference_core.h
  src/main.cpp
  src/post_processor.h
  src/posture_estimating.h
  src/posture_in.h
  src/pre_processor.h
Labels: code

#54 Move unit testing to local
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  README.md
  docs/ci.md
  install.sh
  install_dependencies.sh
  test.sh
Labels: testing
